# docker-compose up 
# docker-compose down 

version: '3'
services:
  database:
    image: circleci/postgres:12 # use latest official postgres version
    environment:
      - POSTGRES_USER=meroxa
      - POSTGRES_PASSWORD=meroxa
      - POSTGRES_DB=meroxa
    ports:
    - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
